#ifndef LWT_LWT_FEATURES_H
#define LWT_LWT_FEATURES_H
#define HAVE_ACCEPT4
#define HAVE_AFFINITY
#define HAVE_EVENTFD
#define HAVE_FDATASYNC
#define HAVE_FD_PASSING
#define HAVE_GETCPU
#define HAVE_GET_CREDENTIALS_LINUX
#define HAVE_PTHREAD
#define HAVE_REENTRANT_HOSTENT
#define HAVE_ST_MTIM_TV_NSEC
#endif
