opam-version: "2.0"
lib: [
  "_build/install/default/lib/dns/META"
  "_build/install/default/lib/dns/cache/dns_cache.a" {"cache/dns_cache.a"}
  "_build/install/default/lib/dns/cache/dns_cache.cma"
    {"cache/dns_cache.cma"}
  "_build/install/default/lib/dns/cache/dns_cache.cmi"
    {"cache/dns_cache.cmi"}
  "_build/install/default/lib/dns/cache/dns_cache.cmt"
    {"cache/dns_cache.cmt"}
  "_build/install/default/lib/dns/cache/dns_cache.cmti"
    {"cache/dns_cache.cmti"}
  "_build/install/default/lib/dns/cache/dns_cache.cmx"
    {"cache/dns_cache.cmx"}
  "_build/install/default/lib/dns/cache/dns_cache.cmxa"
    {"cache/dns_cache.cmxa"}
  "_build/install/default/lib/dns/cache/dns_cache.ml" {"cache/dns_cache.ml"}
  "_build/install/default/lib/dns/cache/dns_cache.mli"
    {"cache/dns_cache.mli"}
  "_build/install/default/lib/dns/dns.a"
  "_build/install/default/lib/dns/dns.cma"
  "_build/install/default/lib/dns/dns.cmi"
  "_build/install/default/lib/dns/dns.cmt"
  "_build/install/default/lib/dns/dns.cmti"
  "_build/install/default/lib/dns/dns.cmx"
  "_build/install/default/lib/dns/dns.cmxa"
  "_build/install/default/lib/dns/dns.ml"
  "_build/install/default/lib/dns/dns.mli"
  "_build/install/default/lib/dns/dune-package"
  "_build/install/default/lib/dns/opam"
]
doc: [
  "_build/install/default/doc/dns/CHANGES.md"
  "_build/install/default/doc/dns/LICENSE.md"
  "_build/install/default/doc/dns/README.md"
]
libexec: [
  "_build/install/default/lib/dns/cache/dns_cache.cmxs"
    {"cache/dns_cache.cmxs"}
  "_build/install/default/lib/dns/dns.cmxs"
]
