opam-version: "2.0"
lib: [
  "_build/install/default/lib/easy-format/META"
  "_build/install/default/lib/easy-format/dune-package"
  "_build/install/default/lib/easy-format/easy_format.a"
  "_build/install/default/lib/easy-format/easy_format.cma"
  "_build/install/default/lib/easy-format/easy_format.cmi"
  "_build/install/default/lib/easy-format/easy_format.cmt"
  "_build/install/default/lib/easy-format/easy_format.cmti"
  "_build/install/default/lib/easy-format/easy_format.cmx"
  "_build/install/default/lib/easy-format/easy_format.cmxa"
  "_build/install/default/lib/easy-format/easy_format.ml"
  "_build/install/default/lib/easy-format/easy_format.mli"
  "_build/install/default/lib/easy-format/opam"
]
doc: [
  "_build/install/default/doc/easy-format/CHANGES.md"
  "_build/install/default/doc/easy-format/LICENSE"
  "_build/install/default/doc/easy-format/README.md"
]
libexec: "_build/install/default/lib/easy-format/easy_format.cmxs"
