opam-version: "2.0"
lib: [
  "_build/install/default/lib/ezjsonm/META"
  "_build/install/default/lib/ezjsonm/dune-package"
  "_build/install/default/lib/ezjsonm/ezjsonm.a"
  "_build/install/default/lib/ezjsonm/ezjsonm.cma"
  "_build/install/default/lib/ezjsonm/ezjsonm.cmi"
  "_build/install/default/lib/ezjsonm/ezjsonm.cmt"
  "_build/install/default/lib/ezjsonm/ezjsonm.cmti"
  "_build/install/default/lib/ezjsonm/ezjsonm.cmx"
  "_build/install/default/lib/ezjsonm/ezjsonm.cmxa"
  "_build/install/default/lib/ezjsonm/ezjsonm.ml"
  "_build/install/default/lib/ezjsonm/ezjsonm.mli"
  "_build/install/default/lib/ezjsonm/opam"
]
doc: [
  "_build/install/default/doc/ezjsonm/CHANGES.md"
  "_build/install/default/doc/ezjsonm/LICENSE"
  "_build/install/default/doc/ezjsonm/README.md"
]
libexec: "_build/install/default/lib/ezjsonm/ezjsonm.cmxs"
