opam-version: "2.0"
lib: [
  "_build/install/default/lib/faraday-lwt/META"
  "_build/install/default/lib/faraday-lwt/dune-package"
  "_build/install/default/lib/faraday-lwt/faraday_lwt.a"
  "_build/install/default/lib/faraday-lwt/faraday_lwt.cma"
  "_build/install/default/lib/faraday-lwt/faraday_lwt.cmi"
  "_build/install/default/lib/faraday-lwt/faraday_lwt.cmt"
  "_build/install/default/lib/faraday-lwt/faraday_lwt.cmti"
  "_build/install/default/lib/faraday-lwt/faraday_lwt.cmx"
  "_build/install/default/lib/faraday-lwt/faraday_lwt.cmxa"
  "_build/install/default/lib/faraday-lwt/faraday_lwt.ml"
  "_build/install/default/lib/faraday-lwt/faraday_lwt.mli"
  "_build/install/default/lib/faraday-lwt/opam"
]
doc: [
  "_build/install/default/doc/faraday-lwt/LICENSE"
  "_build/install/default/doc/faraday-lwt/README.md"
]
libexec: "_build/install/default/lib/faraday-lwt/faraday_lwt.cmxs"
