opam-version: "2.0"
lib: [
  "_build/install/default/lib/faraday/META"
  "_build/install/default/lib/faraday/dune-package"
  "_build/install/default/lib/faraday/faraday.a"
  "_build/install/default/lib/faraday/faraday.cma"
  "_build/install/default/lib/faraday/faraday.cmi"
  "_build/install/default/lib/faraday/faraday.cmt"
  "_build/install/default/lib/faraday/faraday.cmti"
  "_build/install/default/lib/faraday/faraday.cmx"
  "_build/install/default/lib/faraday/faraday.cmxa"
  "_build/install/default/lib/faraday/faraday.ml"
  "_build/install/default/lib/faraday/faraday.mli"
  "_build/install/default/lib/faraday/opam"
]
doc: [
  "_build/install/default/doc/faraday/LICENSE"
  "_build/install/default/doc/faraday/README.md"
]
libexec: "_build/install/default/lib/faraday/faraday.cmxs"
