opam-version: "2.0"
lib: [
  "_build/install/default/lib/happy-eyeballs-lwt/META"
  "_build/install/default/lib/happy-eyeballs-lwt/dune-package"
  "_build/install/default/lib/happy-eyeballs-lwt/happy_eyeballs_lwt.a"
  "_build/install/default/lib/happy-eyeballs-lwt/happy_eyeballs_lwt.cma"
  "_build/install/default/lib/happy-eyeballs-lwt/happy_eyeballs_lwt.cmi"
  "_build/install/default/lib/happy-eyeballs-lwt/happy_eyeballs_lwt.cmt"
  "_build/install/default/lib/happy-eyeballs-lwt/happy_eyeballs_lwt.cmti"
  "_build/install/default/lib/happy-eyeballs-lwt/happy_eyeballs_lwt.cmx"
  "_build/install/default/lib/happy-eyeballs-lwt/happy_eyeballs_lwt.cmxa"
  "_build/install/default/lib/happy-eyeballs-lwt/happy_eyeballs_lwt.ml"
  "_build/install/default/lib/happy-eyeballs-lwt/happy_eyeballs_lwt.mli"
  "_build/install/default/lib/happy-eyeballs-lwt/opam"
]
bin: "_build/install/default/bin/happy_eyeballs_client"
doc: [
  "_build/install/default/doc/happy-eyeballs-lwt/CHANGES.md"
  "_build/install/default/doc/happy-eyeballs-lwt/LICENSE.md"
  "_build/install/default/doc/happy-eyeballs-lwt/README.md"
]
libexec:
  "_build/install/default/lib/happy-eyeballs-lwt/happy_eyeballs_lwt.cmxs"
