opam-version: "2.0"
lib: [
  "_build/install/default/lib/httpaf-lwt-unix/META"
  "_build/install/default/lib/httpaf-lwt-unix/dune-package"
  "_build/install/default/lib/httpaf-lwt-unix/httpaf_lwt_unix.a"
  "_build/install/default/lib/httpaf-lwt-unix/httpaf_lwt_unix.cma"
  "_build/install/default/lib/httpaf-lwt-unix/httpaf_lwt_unix.cmi"
  "_build/install/default/lib/httpaf-lwt-unix/httpaf_lwt_unix.cmt"
  "_build/install/default/lib/httpaf-lwt-unix/httpaf_lwt_unix.cmti"
  "_build/install/default/lib/httpaf-lwt-unix/httpaf_lwt_unix.cmx"
  "_build/install/default/lib/httpaf-lwt-unix/httpaf_lwt_unix.cmxa"
  "_build/install/default/lib/httpaf-lwt-unix/httpaf_lwt_unix.ml"
  "_build/install/default/lib/httpaf-lwt-unix/httpaf_lwt_unix.mli"
  "_build/install/default/lib/httpaf-lwt-unix/opam"
]
doc: [
  "_build/install/default/doc/httpaf-lwt-unix/LICENSE"
  "_build/install/default/doc/httpaf-lwt-unix/README.md"
]
libexec: "_build/install/default/lib/httpaf-lwt-unix/httpaf_lwt_unix.cmxs"
