opam-version: "2.0"
lib: [
  "_build/install/default/lib/lru/META"
  "_build/install/default/lib/lru/dune-package"
  "_build/install/default/lib/lru/lru.a"
  "_build/install/default/lib/lru/lru.cma"
  "_build/install/default/lib/lru/lru.cmi"
  "_build/install/default/lib/lru/lru.cmt"
  "_build/install/default/lib/lru/lru.cmti"
  "_build/install/default/lib/lru/lru.cmx"
  "_build/install/default/lib/lru/lru.cmxa"
  "_build/install/default/lib/lru/lru.ml"
  "_build/install/default/lib/lru/lru.mli"
  "_build/install/default/lib/lru/opam"
]
doc: [
  "_build/install/default/doc/lru/CHANGES.md"
  "_build/install/default/doc/lru/LICENSE.md"
  "_build/install/default/doc/lru/README.md"
]
libexec: "_build/install/default/lib/lru/lru.cmxs"
