opam-version: "2.0"
lib: [
  "_build/install/default/lib/macaddr-cstruct/META"
  "_build/install/default/lib/macaddr-cstruct/dune-package"
  "_build/install/default/lib/macaddr-cstruct/macaddr_cstruct.a"
  "_build/install/default/lib/macaddr-cstruct/macaddr_cstruct.cma"
  "_build/install/default/lib/macaddr-cstruct/macaddr_cstruct.cmi"
  "_build/install/default/lib/macaddr-cstruct/macaddr_cstruct.cmt"
  "_build/install/default/lib/macaddr-cstruct/macaddr_cstruct.cmti"
  "_build/install/default/lib/macaddr-cstruct/macaddr_cstruct.cmx"
  "_build/install/default/lib/macaddr-cstruct/macaddr_cstruct.cmxa"
  "_build/install/default/lib/macaddr-cstruct/macaddr_cstruct.ml"
  "_build/install/default/lib/macaddr-cstruct/macaddr_cstruct.mli"
  "_build/install/default/lib/macaddr-cstruct/opam"
]
doc: [
  "_build/install/default/doc/macaddr-cstruct/CHANGES.md"
  "_build/install/default/doc/macaddr-cstruct/LICENSE.md"
  "_build/install/default/doc/macaddr-cstruct/README.md"
]
libexec: "_build/install/default/lib/macaddr-cstruct/macaddr_cstruct.cmxs"
