opam-version: "2.0"
lib: [
  "_build/install/default/lib/mirage-time/META"
  "_build/install/default/lib/mirage-time/dune-package"
  "_build/install/default/lib/mirage-time/mirage_time.a"
  "_build/install/default/lib/mirage-time/mirage_time.cma"
  "_build/install/default/lib/mirage-time/mirage_time.cmi"
  "_build/install/default/lib/mirage-time/mirage_time.cmt"
  "_build/install/default/lib/mirage-time/mirage_time.cmx"
  "_build/install/default/lib/mirage-time/mirage_time.cmxa"
  "_build/install/default/lib/mirage-time/mirage_time.ml"
  "_build/install/default/lib/mirage-time/opam"
]
doc: [
  "_build/install/default/doc/mirage-time/CHANGES.md"
  "_build/install/default/doc/mirage-time/LICENSE.md"
  "_build/install/default/doc/mirage-time/README.md"
]
libexec: "_build/install/default/lib/mirage-time/mirage_time.cmxs"
