opam-version: "2.0"
lib: [
  "_build/install/default/lib/mirage-random/META"
  "_build/install/default/lib/mirage-random/dune-package"
  "_build/install/default/lib/mirage-random/mirage_random.a"
  "_build/install/default/lib/mirage-random/mirage_random.cma"
  "_build/install/default/lib/mirage-random/mirage_random.cmi"
  "_build/install/default/lib/mirage-random/mirage_random.cmt"
  "_build/install/default/lib/mirage-random/mirage_random.cmx"
  "_build/install/default/lib/mirage-random/mirage_random.cmxa"
  "_build/install/default/lib/mirage-random/mirage_random.ml"
  "_build/install/default/lib/mirage-random/opam"
]
doc: [
  "_build/install/default/doc/mirage-random/CHANGES.md"
  "_build/install/default/doc/mirage-random/LICENSE.md"
  "_build/install/default/doc/mirage-random/README.md"
]
libexec: "_build/install/default/lib/mirage-random/mirage_random.cmxs"
