opam-version: "2.0"
lib: [
  "_build/install/default/lib/mirage-net/META"
  "_build/install/default/lib/mirage-net/dune-package"
  "_build/install/default/lib/mirage-net/mirage_net.a"
  "_build/install/default/lib/mirage-net/mirage_net.cma"
  "_build/install/default/lib/mirage-net/mirage_net.cmi"
  "_build/install/default/lib/mirage-net/mirage_net.cmt"
  "_build/install/default/lib/mirage-net/mirage_net.cmti"
  "_build/install/default/lib/mirage-net/mirage_net.cmx"
  "_build/install/default/lib/mirage-net/mirage_net.cmxa"
  "_build/install/default/lib/mirage-net/mirage_net.ml"
  "_build/install/default/lib/mirage-net/mirage_net.mli"
  "_build/install/default/lib/mirage-net/opam"
]
doc: [
  "_build/install/default/doc/mirage-net/CHANGES.md"
  "_build/install/default/doc/mirage-net/LICENSE.md"
  "_build/install/default/doc/mirage-net/README.md"
]
libexec: "_build/install/default/lib/mirage-net/mirage_net.cmxs"
