opam-version: "2.0"
lib: [
  "_build/install/default/lib/mirage-flow/META"
  "_build/install/default/lib/mirage-flow/dune-package"
  "_build/install/default/lib/mirage-flow/mirage_flow.a"
  "_build/install/default/lib/mirage-flow/mirage_flow.cma"
  "_build/install/default/lib/mirage-flow/mirage_flow.cmi"
  "_build/install/default/lib/mirage-flow/mirage_flow.cmt"
  "_build/install/default/lib/mirage-flow/mirage_flow.cmti"
  "_build/install/default/lib/mirage-flow/mirage_flow.cmx"
  "_build/install/default/lib/mirage-flow/mirage_flow.cmxa"
  "_build/install/default/lib/mirage-flow/mirage_flow.ml"
  "_build/install/default/lib/mirage-flow/mirage_flow.mli"
  "_build/install/default/lib/mirage-flow/opam"
]
doc: [
  "_build/install/default/doc/mirage-flow/CHANGES.md"
  "_build/install/default/doc/mirage-flow/LICENSE.md"
  "_build/install/default/doc/mirage-flow/README.md"
]
libexec: "_build/install/default/lib/mirage-flow/mirage_flow.cmxs"
