opam-version: "2.0"
lib: [
  "_build/install/default/lib/mirage-kv/META"
  "_build/install/default/lib/mirage-kv/dune-package"
  "_build/install/default/lib/mirage-kv/mirage_kv.a"
  "_build/install/default/lib/mirage-kv/mirage_kv.cma"
  "_build/install/default/lib/mirage-kv/mirage_kv.cmi"
  "_build/install/default/lib/mirage-kv/mirage_kv.cmt"
  "_build/install/default/lib/mirage-kv/mirage_kv.cmti"
  "_build/install/default/lib/mirage-kv/mirage_kv.cmx"
  "_build/install/default/lib/mirage-kv/mirage_kv.cmxa"
  "_build/install/default/lib/mirage-kv/mirage_kv.ml"
  "_build/install/default/lib/mirage-kv/mirage_kv.mli"
  "_build/install/default/lib/mirage-kv/opam"
]
doc: [
  "_build/install/default/doc/mirage-kv/CHANGES.md"
  "_build/install/default/doc/mirage-kv/LICENSE.md"
  "_build/install/default/doc/mirage-kv/README.md"
]
libexec: "_build/install/default/lib/mirage-kv/mirage_kv.cmxs"
