opam-version: "2.0"
lib: [
  "_build/install/default/lib/mmap/META"
  "_build/install/default/lib/mmap/dune-package"
  "_build/install/default/lib/mmap/mmap.a"
  "_build/install/default/lib/mmap/mmap.cma"
  "_build/install/default/lib/mmap/mmap.cmi"
  "_build/install/default/lib/mmap/mmap.cmt"
  "_build/install/default/lib/mmap/mmap.cmti"
  "_build/install/default/lib/mmap/mmap.cmx"
  "_build/install/default/lib/mmap/mmap.cmxa"
  "_build/install/default/lib/mmap/mmap.ml"
  "_build/install/default/lib/mmap/mmap.mli"
  "_build/install/default/lib/mmap/opam"
]
doc: [
  "_build/install/default/doc/mmap/CHANGES.md"
  "_build/install/default/doc/mmap/LICENSE"
  "_build/install/default/doc/mmap/README.md"
]
libexec: "_build/install/default/lib/mmap/mmap.cmxs"
