opam-version: "2.0"
lib: [
  "_build/install/default/lib/ocamlformat-rpc-lib/META"
  "_build/install/default/lib/ocamlformat-rpc-lib/dune-package"
  "_build/install/default/lib/ocamlformat-rpc-lib/ocamlformat_rpc_lib.a"
  "_build/install/default/lib/ocamlformat-rpc-lib/ocamlformat_rpc_lib.cma"
  "_build/install/default/lib/ocamlformat-rpc-lib/ocamlformat_rpc_lib.cmi"
  "_build/install/default/lib/ocamlformat-rpc-lib/ocamlformat_rpc_lib.cmt"
  "_build/install/default/lib/ocamlformat-rpc-lib/ocamlformat_rpc_lib.cmti"
  "_build/install/default/lib/ocamlformat-rpc-lib/ocamlformat_rpc_lib.cmx"
  "_build/install/default/lib/ocamlformat-rpc-lib/ocamlformat_rpc_lib.cmxa"
  "_build/install/default/lib/ocamlformat-rpc-lib/ocamlformat_rpc_lib.ml"
  "_build/install/default/lib/ocamlformat-rpc-lib/ocamlformat_rpc_lib.mli"
  "_build/install/default/lib/ocamlformat-rpc-lib/opam"
]
doc: [
  "_build/install/default/doc/ocamlformat-rpc-lib/CHANGES.md"
  "_build/install/default/doc/ocamlformat-rpc-lib/LICENSE.md"
  "_build/install/default/doc/ocamlformat-rpc-lib/README.md"
]
libexec:
  "_build/install/default/lib/ocamlformat-rpc-lib/ocamlformat_rpc_lib.cmxs"
