opam-version: "2.0"
lib: [
  "_build/install/default/lib/ocamlformat/META"
  "_build/install/default/lib/ocamlformat/dune-package"
  "_build/install/default/lib/ocamlformat/opam"
]
bin: "_build/install/default/bin/ocamlformat"
share_root:
  "_build/install/default/share/emacs/site-lisp/ocamlformat.el"
    {"emacs/site-lisp/ocamlformat.el"}
doc: [
  "_build/install/default/doc/ocamlformat/CHANGES.md"
  "_build/install/default/doc/ocamlformat/LICENSE.md"
  "_build/install/default/doc/ocamlformat/README.md"
]
man: "_build/install/default/man/man1/ocamlformat.1"
