opam-version: "2.0"
lib: [
  "_build/install/default/lib/ocplib-endian/META"
  "_build/install/default/lib/ocplib-endian/bigstring/endianBigstring.cmi"
    {"bigstring/endianBigstring.cmi"}
  "_build/install/default/lib/ocplib-endian/bigstring/endianBigstring.cmt"
    {"bigstring/endianBigstring.cmt"}
  "_build/install/default/lib/ocplib-endian/bigstring/endianBigstring.cmti"
    {"bigstring/endianBigstring.cmti"}
  "_build/install/default/lib/ocplib-endian/bigstring/endianBigstring.cmx"
    {"bigstring/endianBigstring.cmx"}
  "_build/install/default/lib/ocplib-endian/bigstring/endianBigstring.ml"
    {"bigstring/endianBigstring.ml"}
  "_build/install/default/lib/ocplib-endian/bigstring/endianBigstring.mli"
    {"bigstring/endianBigstring.mli"}
  "_build/install/default/lib/ocplib-endian/bigstring/ocplib_endian_bigstring.a"
    {"bigstring/ocplib_endian_bigstring.a"}
  "_build/install/default/lib/ocplib-endian/bigstring/ocplib_endian_bigstring.cma"
    {"bigstring/ocplib_endian_bigstring.cma"}
  "_build/install/default/lib/ocplib-endian/bigstring/ocplib_endian_bigstring.cmxa"
    {"bigstring/ocplib_endian_bigstring.cmxa"}
  "_build/install/default/lib/ocplib-endian/dune-package"
  "_build/install/default/lib/ocplib-endian/endianBytes.cmi"
  "_build/install/default/lib/ocplib-endian/endianBytes.cmt"
  "_build/install/default/lib/ocplib-endian/endianBytes.cmti"
  "_build/install/default/lib/ocplib-endian/endianBytes.cmx"
  "_build/install/default/lib/ocplib-endian/endianBytes.ml"
  "_build/install/default/lib/ocplib-endian/endianBytes.mli"
  "_build/install/default/lib/ocplib-endian/endianString.cmi"
  "_build/install/default/lib/ocplib-endian/endianString.cmt"
  "_build/install/default/lib/ocplib-endian/endianString.cmti"
  "_build/install/default/lib/ocplib-endian/endianString.cmx"
  "_build/install/default/lib/ocplib-endian/endianString.ml"
  "_build/install/default/lib/ocplib-endian/endianString.mli"
  "_build/install/default/lib/ocplib-endian/ocplib_endian.a"
  "_build/install/default/lib/ocplib-endian/ocplib_endian.cma"
  "_build/install/default/lib/ocplib-endian/ocplib_endian.cmxa"
  "_build/install/default/lib/ocplib-endian/opam"
]
doc: [
  "_build/install/default/doc/ocplib-endian/CHANGES.md"
  "_build/install/default/doc/ocplib-endian/README.md"
]
libexec: [
  "_build/install/default/lib/ocplib-endian/bigstring/ocplib_endian_bigstring.cmxs"
    {"bigstring/ocplib_endian_bigstring.cmxs"}
  "_build/install/default/lib/ocplib-endian/ocplib_endian.cmxs"
]
