opam-version: "2.0"
lib: [
  "_build/install/default/lib/odoc/META"
  "_build/install/default/lib/odoc/document/ML.ml" {"document/ML.ml"}
  "_build/install/default/lib/odoc/document/ML.mli" {"document/ML.mli"}
  "_build/install/default/lib/odoc/document/codefmt.ml"
    {"document/codefmt.ml"}
  "_build/install/default/lib/odoc/document/comment.ml"
    {"document/comment.ml"}
  "_build/install/default/lib/odoc/document/doctree.ml"
    {"document/doctree.ml"}
  "_build/install/default/lib/odoc/document/generator.ml"
    {"document/generator.ml"}
  "_build/install/default/lib/odoc/document/generator.mli"
    {"document/generator.mli"}
  "_build/install/default/lib/odoc/document/generator_signatures.ml"
    {"document/generator_signatures.ml"}
  "_build/install/default/lib/odoc/document/odoc_document.a"
    {"document/odoc_document.a"}
  "_build/install/default/lib/odoc/document/odoc_document.cma"
    {"document/odoc_document.cma"}
  "_build/install/default/lib/odoc/document/odoc_document.cmi"
    {"document/odoc_document.cmi"}
  "_build/install/default/lib/odoc/document/odoc_document.cmt"
    {"document/odoc_document.cmt"}
  "_build/install/default/lib/odoc/document/odoc_document.cmx"
    {"document/odoc_document.cmx"}
  "_build/install/default/lib/odoc/document/odoc_document.cmxa"
    {"document/odoc_document.cmxa"}
  "_build/install/default/lib/odoc/document/odoc_document.ml"
    {"document/odoc_document.ml"}
  "_build/install/default/lib/odoc/document/odoc_document__Codefmt.cmi"
    {"document/odoc_document__Codefmt.cmi"}
  "_build/install/default/lib/odoc/document/odoc_document__Codefmt.cmt"
    {"document/odoc_document__Codefmt.cmt"}
  "_build/install/default/lib/odoc/document/odoc_document__Codefmt.cmx"
    {"document/odoc_document__Codefmt.cmx"}
  "_build/install/default/lib/odoc/document/odoc_document__Comment.cmi"
    {"document/odoc_document__Comment.cmi"}
  "_build/install/default/lib/odoc/document/odoc_document__Comment.cmt"
    {"document/odoc_document__Comment.cmt"}
  "_build/install/default/lib/odoc/document/odoc_document__Comment.cmx"
    {"document/odoc_document__Comment.cmx"}
  "_build/install/default/lib/odoc/document/odoc_document__Doctree.cmi"
    {"document/odoc_document__Doctree.cmi"}
  "_build/install/default/lib/odoc/document/odoc_document__Doctree.cmt"
    {"document/odoc_document__Doctree.cmt"}
  "_build/install/default/lib/odoc/document/odoc_document__Doctree.cmx"
    {"document/odoc_document__Doctree.cmx"}
  "_build/install/default/lib/odoc/document/odoc_document__Generator.cmi"
    {"document/odoc_document__Generator.cmi"}
  "_build/install/default/lib/odoc/document/odoc_document__Generator.cmt"
    {"document/odoc_document__Generator.cmt"}
  "_build/install/default/lib/odoc/document/odoc_document__Generator.cmti"
    {"document/odoc_document__Generator.cmti"}
  "_build/install/default/lib/odoc/document/odoc_document__Generator.cmx"
    {"document/odoc_document__Generator.cmx"}
  "_build/install/default/lib/odoc/document/odoc_document__Generator_signatures.cmi"
    {"document/odoc_document__Generator_signatures.cmi"}
  "_build/install/default/lib/odoc/document/odoc_document__Generator_signatures.cmt"
    {"document/odoc_document__Generator_signatures.cmt"}
  "_build/install/default/lib/odoc/document/odoc_document__Generator_signatures.cmx"
    {"document/odoc_document__Generator_signatures.cmx"}
  "_build/install/default/lib/odoc/document/odoc_document__ML.cmi"
    {"document/odoc_document__ML.cmi"}
  "_build/install/default/lib/odoc/document/odoc_document__ML.cmt"
    {"document/odoc_document__ML.cmt"}
  "_build/install/default/lib/odoc/document/odoc_document__ML.cmti"
    {"document/odoc_document__ML.cmti"}
  "_build/install/default/lib/odoc/document/odoc_document__ML.cmx"
    {"document/odoc_document__ML.cmx"}
  "_build/install/default/lib/odoc/document/odoc_document__Reason.cmi"
    {"document/odoc_document__Reason.cmi"}
  "_build/install/default/lib/odoc/document/odoc_document__Reason.cmt"
    {"document/odoc_document__Reason.cmt"}
  "_build/install/default/lib/odoc/document/odoc_document__Reason.cmti"
    {"document/odoc_document__Reason.cmti"}
  "_build/install/default/lib/odoc/document/odoc_document__Reason.cmx"
    {"document/odoc_document__Reason.cmx"}
  "_build/install/default/lib/odoc/document/odoc_document__Renderer.cmi"
    {"document/odoc_document__Renderer.cmi"}
  "_build/install/default/lib/odoc/document/odoc_document__Renderer.cmt"
    {"document/odoc_document__Renderer.cmt"}
  "_build/install/default/lib/odoc/document/odoc_document__Renderer.cmx"
    {"document/odoc_document__Renderer.cmx"}
  "_build/install/default/lib/odoc/document/odoc_document__Targets.cmi"
    {"document/odoc_document__Targets.cmi"}
  "_build/install/default/lib/odoc/document/odoc_document__Targets.cmt"
    {"document/odoc_document__Targets.cmt"}
  "_build/install/default/lib/odoc/document/odoc_document__Targets.cmti"
    {"document/odoc_document__Targets.cmti"}
  "_build/install/default/lib/odoc/document/odoc_document__Targets.cmx"
    {"document/odoc_document__Targets.cmx"}
  "_build/install/default/lib/odoc/document/odoc_document__Types.cmi"
    {"document/odoc_document__Types.cmi"}
  "_build/install/default/lib/odoc/document/odoc_document__Types.cmt"
    {"document/odoc_document__Types.cmt"}
  "_build/install/default/lib/odoc/document/odoc_document__Types.cmx"
    {"document/odoc_document__Types.cmx"}
  "_build/install/default/lib/odoc/document/odoc_document__Url.cmi"
    {"document/odoc_document__Url.cmi"}
  "_build/install/default/lib/odoc/document/odoc_document__Url.cmt"
    {"document/odoc_document__Url.cmt"}
  "_build/install/default/lib/odoc/document/odoc_document__Url.cmti"
    {"document/odoc_document__Url.cmti"}
  "_build/install/default/lib/odoc/document/odoc_document__Url.cmx"
    {"document/odoc_document__Url.cmx"}
  "_build/install/default/lib/odoc/document/odoc_document__Utils.cmi"
    {"document/odoc_document__Utils.cmi"}
  "_build/install/default/lib/odoc/document/odoc_document__Utils.cmt"
    {"document/odoc_document__Utils.cmt"}
  "_build/install/default/lib/odoc/document/odoc_document__Utils.cmx"
    {"document/odoc_document__Utils.cmx"}
  "_build/install/default/lib/odoc/document/reason.ml" {"document/reason.ml"}
  "_build/install/default/lib/odoc/document/reason.mli"
    {"document/reason.mli"}
  "_build/install/default/lib/odoc/document/renderer.ml"
    {"document/renderer.ml"}
  "_build/install/default/lib/odoc/document/targets.ml"
    {"document/targets.ml"}
  "_build/install/default/lib/odoc/document/targets.mli"
    {"document/targets.mli"}
  "_build/install/default/lib/odoc/document/types.ml" {"document/types.ml"}
  "_build/install/default/lib/odoc/document/url.ml" {"document/url.ml"}
  "_build/install/default/lib/odoc/document/url.mli" {"document/url.mli"}
  "_build/install/default/lib/odoc/document/utils.ml" {"document/utils.ml"}
  "_build/install/default/lib/odoc/dune-package"
  "_build/install/default/lib/odoc/examples/expansion.mli"
    {"examples/expansion.mli"}
  "_build/install/default/lib/odoc/examples/markup.mli"
    {"examples/markup.mli"}
  "_build/install/default/lib/odoc/examples/odoc_examples.a"
    {"examples/odoc_examples.a"}
  "_build/install/default/lib/odoc/examples/odoc_examples.cma"
    {"examples/odoc_examples.cma"}
  "_build/install/default/lib/odoc/examples/odoc_examples.cmi"
    {"examples/odoc_examples.cmi"}
  "_build/install/default/lib/odoc/examples/odoc_examples.cmt"
    {"examples/odoc_examples.cmt"}
  "_build/install/default/lib/odoc/examples/odoc_examples.cmx"
    {"examples/odoc_examples.cmx"}
  "_build/install/default/lib/odoc/examples/odoc_examples.cmxa"
    {"examples/odoc_examples.cmxa"}
  "_build/install/default/lib/odoc/examples/odoc_examples.ml"
    {"examples/odoc_examples.ml"}
  "_build/install/default/lib/odoc/examples/odoc_examples__.cmi"
    {"examples/odoc_examples__.cmi"}
  "_build/install/default/lib/odoc/examples/odoc_examples__.cmt"
    {"examples/odoc_examples__.cmt"}
  "_build/install/default/lib/odoc/examples/odoc_examples__.cmx"
    {"examples/odoc_examples__.cmx"}
  "_build/install/default/lib/odoc/examples/odoc_examples__.ml"
    {"examples/odoc_examples__.ml"}
  "_build/install/default/lib/odoc/examples/odoc_examples__Expansion.cmi"
    {"examples/odoc_examples__Expansion.cmi"}
  "_build/install/default/lib/odoc/examples/odoc_examples__Expansion.cmti"
    {"examples/odoc_examples__Expansion.cmti"}
  "_build/install/default/lib/odoc/examples/odoc_examples__Markup.cmi"
    {"examples/odoc_examples__Markup.cmi"}
  "_build/install/default/lib/odoc/examples/odoc_examples__Markup.cmti"
    {"examples/odoc_examples__Markup.cmti"}
  "_build/install/default/lib/odoc/examples/odoc_examples__Resolution.cmi"
    {"examples/odoc_examples__Resolution.cmi"}
  "_build/install/default/lib/odoc/examples/odoc_examples__Resolution.cmti"
    {"examples/odoc_examples__Resolution.cmti"}
  "_build/install/default/lib/odoc/examples/odoc_examples__Unexposed.cmi"
    {"examples/odoc_examples__Unexposed.cmi"}
  "_build/install/default/lib/odoc/examples/odoc_examples__Unexposed.cmti"
    {"examples/odoc_examples__Unexposed.cmti"}
  "_build/install/default/lib/odoc/examples/odoc_examples__Wrapping.cmi"
    {"examples/odoc_examples__Wrapping.cmi"}
  "_build/install/default/lib/odoc/examples/odoc_examples__Wrapping.cmti"
    {"examples/odoc_examples__Wrapping.cmti"}
  "_build/install/default/lib/odoc/examples/resolution.mli"
    {"examples/resolution.mli"}
  "_build/install/default/lib/odoc/examples/unexposed.mli"
    {"examples/unexposed.mli"}
  "_build/install/default/lib/odoc/examples/wrapping.mli"
    {"examples/wrapping.mli"}
  "_build/install/default/lib/odoc/html/generator.ml" {"html/generator.ml"}
  "_build/install/default/lib/odoc/html/generator.mli" {"html/generator.mli"}
  "_build/install/default/lib/odoc/html/link.ml" {"html/link.ml"}
  "_build/install/default/lib/odoc/html/link.mli" {"html/link.mli"}
  "_build/install/default/lib/odoc/html/odoc_html.a" {"html/odoc_html.a"}
  "_build/install/default/lib/odoc/html/odoc_html.cma" {"html/odoc_html.cma"}
  "_build/install/default/lib/odoc/html/odoc_html.cmi" {"html/odoc_html.cmi"}
  "_build/install/default/lib/odoc/html/odoc_html.cmt" {"html/odoc_html.cmt"}
  "_build/install/default/lib/odoc/html/odoc_html.cmx" {"html/odoc_html.cmx"}
  "_build/install/default/lib/odoc/html/odoc_html.cmxa"
    {"html/odoc_html.cmxa"}
  "_build/install/default/lib/odoc/html/odoc_html.ml" {"html/odoc_html.ml"}
  "_build/install/default/lib/odoc/html/odoc_html__.cmi"
    {"html/odoc_html__.cmi"}
  "_build/install/default/lib/odoc/html/odoc_html__.cmt"
    {"html/odoc_html__.cmt"}
  "_build/install/default/lib/odoc/html/odoc_html__.cmx"
    {"html/odoc_html__.cmx"}
  "_build/install/default/lib/odoc/html/odoc_html__.ml"
    {"html/odoc_html__.ml"}
  "_build/install/default/lib/odoc/html/odoc_html__Generator.cmi"
    {"html/odoc_html__Generator.cmi"}
  "_build/install/default/lib/odoc/html/odoc_html__Generator.cmt"
    {"html/odoc_html__Generator.cmt"}
  "_build/install/default/lib/odoc/html/odoc_html__Generator.cmti"
    {"html/odoc_html__Generator.cmti"}
  "_build/install/default/lib/odoc/html/odoc_html__Generator.cmx"
    {"html/odoc_html__Generator.cmx"}
  "_build/install/default/lib/odoc/html/odoc_html__Link.cmi"
    {"html/odoc_html__Link.cmi"}
  "_build/install/default/lib/odoc/html/odoc_html__Link.cmt"
    {"html/odoc_html__Link.cmt"}
  "_build/install/default/lib/odoc/html/odoc_html__Link.cmti"
    {"html/odoc_html__Link.cmti"}
  "_build/install/default/lib/odoc/html/odoc_html__Link.cmx"
    {"html/odoc_html__Link.cmx"}
  "_build/install/default/lib/odoc/html/odoc_html__Tree.cmi"
    {"html/odoc_html__Tree.cmi"}
  "_build/install/default/lib/odoc/html/odoc_html__Tree.cmt"
    {"html/odoc_html__Tree.cmt"}
  "_build/install/default/lib/odoc/html/odoc_html__Tree.cmti"
    {"html/odoc_html__Tree.cmti"}
  "_build/install/default/lib/odoc/html/odoc_html__Tree.cmx"
    {"html/odoc_html__Tree.cmx"}
  "_build/install/default/lib/odoc/html/odoc_html__Utils.cmi"
    {"html/odoc_html__Utils.cmi"}
  "_build/install/default/lib/odoc/html/odoc_html__Utils.cmt"
    {"html/odoc_html__Utils.cmt"}
  "_build/install/default/lib/odoc/html/odoc_html__Utils.cmx"
    {"html/odoc_html__Utils.cmx"}
  "_build/install/default/lib/odoc/html/tree.ml" {"html/tree.ml"}
  "_build/install/default/lib/odoc/html/tree.mli" {"html/tree.mli"}
  "_build/install/default/lib/odoc/html/utils.ml" {"html/utils.ml"}
  "_build/install/default/lib/odoc/latex/generator.ml" {"latex/generator.ml"}
  "_build/install/default/lib/odoc/latex/generator.mli"
    {"latex/generator.mli"}
  "_build/install/default/lib/odoc/latex/odoc_latex.a" {"latex/odoc_latex.a"}
  "_build/install/default/lib/odoc/latex/odoc_latex.cma"
    {"latex/odoc_latex.cma"}
  "_build/install/default/lib/odoc/latex/odoc_latex.cmi"
    {"latex/odoc_latex.cmi"}
  "_build/install/default/lib/odoc/latex/odoc_latex.cmt"
    {"latex/odoc_latex.cmt"}
  "_build/install/default/lib/odoc/latex/odoc_latex.cmx"
    {"latex/odoc_latex.cmx"}
  "_build/install/default/lib/odoc/latex/odoc_latex.cmxa"
    {"latex/odoc_latex.cmxa"}
  "_build/install/default/lib/odoc/latex/odoc_latex.ml"
    {"latex/odoc_latex.ml"}
  "_build/install/default/lib/odoc/latex/odoc_latex__Generator.cmi"
    {"latex/odoc_latex__Generator.cmi"}
  "_build/install/default/lib/odoc/latex/odoc_latex__Generator.cmt"
    {"latex/odoc_latex__Generator.cmt"}
  "_build/install/default/lib/odoc/latex/odoc_latex__Generator.cmti"
    {"latex/odoc_latex__Generator.cmti"}
  "_build/install/default/lib/odoc/latex/odoc_latex__Generator.cmx"
    {"latex/odoc_latex__Generator.cmx"}
  "_build/install/default/lib/odoc/latex/odoc_latex__Raw.cmi"
    {"latex/odoc_latex__Raw.cmi"}
  "_build/install/default/lib/odoc/latex/odoc_latex__Raw.cmt"
    {"latex/odoc_latex__Raw.cmt"}
  "_build/install/default/lib/odoc/latex/odoc_latex__Raw.cmti"
    {"latex/odoc_latex__Raw.cmti"}
  "_build/install/default/lib/odoc/latex/odoc_latex__Raw.cmx"
    {"latex/odoc_latex__Raw.cmx"}
  "_build/install/default/lib/odoc/latex/odoc_latex__Types.cmi"
    {"latex/odoc_latex__Types.cmi"}
  "_build/install/default/lib/odoc/latex/odoc_latex__Types.cmt"
    {"latex/odoc_latex__Types.cmt"}
  "_build/install/default/lib/odoc/latex/odoc_latex__Types.cmx"
    {"latex/odoc_latex__Types.cmx"}
  "_build/install/default/lib/odoc/latex/raw.ml" {"latex/raw.ml"}
  "_build/install/default/lib/odoc/latex/raw.mli" {"latex/raw.mli"}
  "_build/install/default/lib/odoc/latex/types.ml" {"latex/types.ml"}
  "_build/install/default/lib/odoc/loader/cmi.ml" {"loader/cmi.ml"}
  "_build/install/default/lib/odoc/loader/cmi.mli" {"loader/cmi.mli"}
  "_build/install/default/lib/odoc/loader/cmt.ml" {"loader/cmt.ml"}
  "_build/install/default/lib/odoc/loader/cmt.mli" {"loader/cmt.mli"}
  "_build/install/default/lib/odoc/loader/cmti.ml" {"loader/cmti.ml"}
  "_build/install/default/lib/odoc/loader/cmti.mli" {"loader/cmti.mli"}
  "_build/install/default/lib/odoc/loader/doc_attr.ml" {"loader/doc_attr.ml"}
  "_build/install/default/lib/odoc/loader/doc_attr.mli"
    {"loader/doc_attr.mli"}
  "_build/install/default/lib/odoc/loader/ident_env.ml"
    {"loader/ident_env.ml"}
  "_build/install/default/lib/odoc/loader/ident_env.mli"
    {"loader/ident_env.mli"}
  "_build/install/default/lib/odoc/loader/odoc_loader.a"
    {"loader/odoc_loader.a"}
  "_build/install/default/lib/odoc/loader/odoc_loader.cma"
    {"loader/odoc_loader.cma"}
  "_build/install/default/lib/odoc/loader/odoc_loader.cmi"
    {"loader/odoc_loader.cmi"}
  "_build/install/default/lib/odoc/loader/odoc_loader.cmt"
    {"loader/odoc_loader.cmt"}
  "_build/install/default/lib/odoc/loader/odoc_loader.cmti"
    {"loader/odoc_loader.cmti"}
  "_build/install/default/lib/odoc/loader/odoc_loader.cmx"
    {"loader/odoc_loader.cmx"}
  "_build/install/default/lib/odoc/loader/odoc_loader.cmxa"
    {"loader/odoc_loader.cmxa"}
  "_build/install/default/lib/odoc/loader/odoc_loader.ml"
    {"loader/odoc_loader.ml"}
  "_build/install/default/lib/odoc/loader/odoc_loader.mli"
    {"loader/odoc_loader.mli"}
  "_build/install/default/lib/odoc/loader/odoc_loader__.cmi"
    {"loader/odoc_loader__.cmi"}
  "_build/install/default/lib/odoc/loader/odoc_loader__.cmt"
    {"loader/odoc_loader__.cmt"}
  "_build/install/default/lib/odoc/loader/odoc_loader__.cmx"
    {"loader/odoc_loader__.cmx"}
  "_build/install/default/lib/odoc/loader/odoc_loader__.ml"
    {"loader/odoc_loader__.ml"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Cmi.cmi"
    {"loader/odoc_loader__Cmi.cmi"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Cmi.cmt"
    {"loader/odoc_loader__Cmi.cmt"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Cmi.cmti"
    {"loader/odoc_loader__Cmi.cmti"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Cmi.cmx"
    {"loader/odoc_loader__Cmi.cmx"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Cmt.cmi"
    {"loader/odoc_loader__Cmt.cmi"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Cmt.cmt"
    {"loader/odoc_loader__Cmt.cmt"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Cmt.cmti"
    {"loader/odoc_loader__Cmt.cmti"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Cmt.cmx"
    {"loader/odoc_loader__Cmt.cmx"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Cmti.cmi"
    {"loader/odoc_loader__Cmti.cmi"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Cmti.cmt"
    {"loader/odoc_loader__Cmti.cmt"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Cmti.cmti"
    {"loader/odoc_loader__Cmti.cmti"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Cmti.cmx"
    {"loader/odoc_loader__Cmti.cmx"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Doc_attr.cmi"
    {"loader/odoc_loader__Doc_attr.cmi"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Doc_attr.cmt"
    {"loader/odoc_loader__Doc_attr.cmt"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Doc_attr.cmti"
    {"loader/odoc_loader__Doc_attr.cmti"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Doc_attr.cmx"
    {"loader/odoc_loader__Doc_attr.cmx"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Ident_env.cmi"
    {"loader/odoc_loader__Ident_env.cmi"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Ident_env.cmt"
    {"loader/odoc_loader__Ident_env.cmt"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Ident_env.cmti"
    {"loader/odoc_loader__Ident_env.cmti"}
  "_build/install/default/lib/odoc/loader/odoc_loader__Ident_env.cmx"
    {"loader/odoc_loader__Ident_env.cmx"}
  "_build/install/default/lib/odoc/manpage/generator.ml"
    {"manpage/generator.ml"}
  "_build/install/default/lib/odoc/manpage/generator.mli"
    {"manpage/generator.mli"}
  "_build/install/default/lib/odoc/manpage/link.ml" {"manpage/link.ml"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage.a"
    {"manpage/odoc_manpage.a"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage.cma"
    {"manpage/odoc_manpage.cma"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage.cmi"
    {"manpage/odoc_manpage.cmi"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage.cmt"
    {"manpage/odoc_manpage.cmt"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage.cmx"
    {"manpage/odoc_manpage.cmx"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage.cmxa"
    {"manpage/odoc_manpage.cmxa"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage.ml"
    {"manpage/odoc_manpage.ml"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage__Generator.cmi"
    {"manpage/odoc_manpage__Generator.cmi"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage__Generator.cmt"
    {"manpage/odoc_manpage__Generator.cmt"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage__Generator.cmti"
    {"manpage/odoc_manpage__Generator.cmti"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage__Generator.cmx"
    {"manpage/odoc_manpage__Generator.cmx"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage__Link.cmi"
    {"manpage/odoc_manpage__Link.cmi"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage__Link.cmt"
    {"manpage/odoc_manpage__Link.cmt"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage__Link.cmx"
    {"manpage/odoc_manpage__Link.cmx"}
  "_build/install/default/lib/odoc/model/comment.ml" {"model/comment.ml"}
  "_build/install/default/lib/odoc/model/compat.ml" {"model/compat.ml"}
  "_build/install/default/lib/odoc/model/error.ml" {"model/error.ml"}
  "_build/install/default/lib/odoc/model/error.mli" {"model/error.mli"}
  "_build/install/default/lib/odoc/model/lang.ml" {"model/lang.ml"}
  "_build/install/default/lib/odoc/model/location_.ml" {"model/location_.ml"}
  "_build/install/default/lib/odoc/model/location_.mli"
    {"model/location_.mli"}
  "_build/install/default/lib/odoc/model/names.ml" {"model/names.ml"}
  "_build/install/default/lib/odoc/model/names.mli" {"model/names.mli"}
  "_build/install/default/lib/odoc/model/odoc_model.a" {"model/odoc_model.a"}
  "_build/install/default/lib/odoc/model/odoc_model.cma"
    {"model/odoc_model.cma"}
  "_build/install/default/lib/odoc/model/odoc_model.cmi"
    {"model/odoc_model.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model.cmt"
    {"model/odoc_model.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model.cmx"
    {"model/odoc_model.cmx"}
  "_build/install/default/lib/odoc/model/odoc_model.cmxa"
    {"model/odoc_model.cmxa"}
  "_build/install/default/lib/odoc/model/odoc_model.ml"
    {"model/odoc_model.ml"}
  "_build/install/default/lib/odoc/model/odoc_model__.cmi"
    {"model/odoc_model__.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model__.cmt"
    {"model/odoc_model__.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model__.cmx"
    {"model/odoc_model__.cmx"}
  "_build/install/default/lib/odoc/model/odoc_model__.ml"
    {"model/odoc_model__.ml"}
  "_build/install/default/lib/odoc/model/odoc_model__Comment.cmi"
    {"model/odoc_model__Comment.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model__Comment.cmt"
    {"model/odoc_model__Comment.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model__Comment.cmx"
    {"model/odoc_model__Comment.cmx"}
  "_build/install/default/lib/odoc/model/odoc_model__Compat.cmi"
    {"model/odoc_model__Compat.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model__Compat.cmt"
    {"model/odoc_model__Compat.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model__Compat.cmx"
    {"model/odoc_model__Compat.cmx"}
  "_build/install/default/lib/odoc/model/odoc_model__Error.cmi"
    {"model/odoc_model__Error.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model__Error.cmt"
    {"model/odoc_model__Error.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model__Error.cmti"
    {"model/odoc_model__Error.cmti"}
  "_build/install/default/lib/odoc/model/odoc_model__Error.cmx"
    {"model/odoc_model__Error.cmx"}
  "_build/install/default/lib/odoc/model/odoc_model__Lang.cmi"
    {"model/odoc_model__Lang.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model__Lang.cmt"
    {"model/odoc_model__Lang.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model__Lang.cmx"
    {"model/odoc_model__Lang.cmx"}
  "_build/install/default/lib/odoc/model/odoc_model__Location_.cmi"
    {"model/odoc_model__Location_.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model__Location_.cmt"
    {"model/odoc_model__Location_.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model__Location_.cmti"
    {"model/odoc_model__Location_.cmti"}
  "_build/install/default/lib/odoc/model/odoc_model__Location_.cmx"
    {"model/odoc_model__Location_.cmx"}
  "_build/install/default/lib/odoc/model/odoc_model__Names.cmi"
    {"model/odoc_model__Names.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model__Names.cmt"
    {"model/odoc_model__Names.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model__Names.cmti"
    {"model/odoc_model__Names.cmti"}
  "_build/install/default/lib/odoc/model/odoc_model__Names.cmx"
    {"model/odoc_model__Names.cmx"}
  "_build/install/default/lib/odoc/model/odoc_model__Paths.cmi"
    {"model/odoc_model__Paths.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model__Paths.cmt"
    {"model/odoc_model__Paths.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model__Paths.cmti"
    {"model/odoc_model__Paths.cmti"}
  "_build/install/default/lib/odoc/model/odoc_model__Paths.cmx"
    {"model/odoc_model__Paths.cmx"}
  "_build/install/default/lib/odoc/model/odoc_model__Paths_types.cmi"
    {"model/odoc_model__Paths_types.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model__Paths_types.cmt"
    {"model/odoc_model__Paths_types.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model__Paths_types.cmx"
    {"model/odoc_model__Paths_types.cmx"}
  "_build/install/default/lib/odoc/model/odoc_model__Predefined.cmi"
    {"model/odoc_model__Predefined.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model__Predefined.cmt"
    {"model/odoc_model__Predefined.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model__Predefined.cmti"
    {"model/odoc_model__Predefined.cmti"}
  "_build/install/default/lib/odoc/model/odoc_model__Predefined.cmx"
    {"model/odoc_model__Predefined.cmx"}
  "_build/install/default/lib/odoc/model/odoc_model__Reference.cmi"
    {"model/odoc_model__Reference.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model__Reference.cmt"
    {"model/odoc_model__Reference.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model__Reference.cmti"
    {"model/odoc_model__Reference.cmti"}
  "_build/install/default/lib/odoc/model/odoc_model__Reference.cmx"
    {"model/odoc_model__Reference.cmx"}
  "_build/install/default/lib/odoc/model/odoc_model__Root.cmi"
    {"model/odoc_model__Root.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model__Root.cmt"
    {"model/odoc_model__Root.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model__Root.cmti"
    {"model/odoc_model__Root.cmti"}
  "_build/install/default/lib/odoc/model/odoc_model__Root.cmx"
    {"model/odoc_model__Root.cmx"}
  "_build/install/default/lib/odoc/model/odoc_model__Semantics.cmi"
    {"model/odoc_model__Semantics.cmi"}
  "_build/install/default/lib/odoc/model/odoc_model__Semantics.cmt"
    {"model/odoc_model__Semantics.cmt"}
  "_build/install/default/lib/odoc/model/odoc_model__Semantics.cmti"
    {"model/odoc_model__Semantics.cmti"}
  "_build/install/default/lib/odoc/model/odoc_model__Semantics.cmx"
    {"model/odoc_model__Semantics.cmx"}
  "_build/install/default/lib/odoc/model/paths.ml" {"model/paths.ml"}
  "_build/install/default/lib/odoc/model/paths.mli" {"model/paths.mli"}
  "_build/install/default/lib/odoc/model/paths_types.ml"
    {"model/paths_types.ml"}
  "_build/install/default/lib/odoc/model/predefined.ml"
    {"model/predefined.ml"}
  "_build/install/default/lib/odoc/model/predefined.mli"
    {"model/predefined.mli"}
  "_build/install/default/lib/odoc/model/reference.ml" {"model/reference.ml"}
  "_build/install/default/lib/odoc/model/reference.mli"
    {"model/reference.mli"}
  "_build/install/default/lib/odoc/model/root.ml" {"model/root.ml"}
  "_build/install/default/lib/odoc/model/root.mli" {"model/root.mli"}
  "_build/install/default/lib/odoc/model/semantics.ml" {"model/semantics.ml"}
  "_build/install/default/lib/odoc/model/semantics.mli"
    {"model/semantics.mli"}
  "_build/install/default/lib/odoc/model_desc/comment_desc.ml"
    {"model_desc/comment_desc.ml"}
  "_build/install/default/lib/odoc/model_desc/comment_desc.mli"
    {"model_desc/comment_desc.mli"}
  "_build/install/default/lib/odoc/model_desc/lang_desc.ml"
    {"model_desc/lang_desc.ml"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc.a"
    {"model_desc/odoc_model_desc.a"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc.cma"
    {"model_desc/odoc_model_desc.cma"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc.cmi"
    {"model_desc/odoc_model_desc.cmi"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc.cmt"
    {"model_desc/odoc_model_desc.cmt"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc.cmx"
    {"model_desc/odoc_model_desc.cmx"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc.cmxa"
    {"model_desc/odoc_model_desc.cmxa"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc.ml"
    {"model_desc/odoc_model_desc.ml"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Comment_desc.cmi"
    {"model_desc/odoc_model_desc__Comment_desc.cmi"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Comment_desc.cmt"
    {"model_desc/odoc_model_desc__Comment_desc.cmt"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Comment_desc.cmti"
    {"model_desc/odoc_model_desc__Comment_desc.cmti"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Comment_desc.cmx"
    {"model_desc/odoc_model_desc__Comment_desc.cmx"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Lang_desc.cmi"
    {"model_desc/odoc_model_desc__Lang_desc.cmi"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Lang_desc.cmt"
    {"model_desc/odoc_model_desc__Lang_desc.cmt"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Lang_desc.cmx"
    {"model_desc/odoc_model_desc__Lang_desc.cmx"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Paths_desc.cmi"
    {"model_desc/odoc_model_desc__Paths_desc.cmi"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Paths_desc.cmt"
    {"model_desc/odoc_model_desc__Paths_desc.cmt"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Paths_desc.cmti"
    {"model_desc/odoc_model_desc__Paths_desc.cmti"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Paths_desc.cmx"
    {"model_desc/odoc_model_desc__Paths_desc.cmx"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Type_desc.cmi"
    {"model_desc/odoc_model_desc__Type_desc.cmi"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Type_desc.cmt"
    {"model_desc/odoc_model_desc__Type_desc.cmt"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc__Type_desc.cmx"
    {"model_desc/odoc_model_desc__Type_desc.cmx"}
  "_build/install/default/lib/odoc/model_desc/paths_desc.ml"
    {"model_desc/paths_desc.ml"}
  "_build/install/default/lib/odoc/model_desc/paths_desc.mli"
    {"model_desc/paths_desc.mli"}
  "_build/install/default/lib/odoc/model_desc/type_desc.ml"
    {"model_desc/type_desc.ml"}
  "_build/install/default/lib/odoc/ocamlary/ocamlary.cmi"
    {"ocamlary/ocamlary.cmi"}
  "_build/install/default/lib/odoc/ocamlary/ocamlary.cmti"
    {"ocamlary/ocamlary.cmti"}
  "_build/install/default/lib/odoc/ocamlary/ocamlary.mli"
    {"ocamlary/ocamlary.mli"}
  "_build/install/default/lib/odoc/odoc/compile.ml" {"odoc/compile.ml"}
  "_build/install/default/lib/odoc/odoc/compile.mli" {"odoc/compile.mli"}
  "_build/install/default/lib/odoc/odoc/css_file.ml" {"odoc/css_file.ml"}
  "_build/install/default/lib/odoc/odoc/depends.ml" {"odoc/depends.ml"}
  "_build/install/default/lib/odoc/odoc/depends.mli" {"odoc/depends.mli"}
  "_build/install/default/lib/odoc/odoc/fs.ml" {"odoc/fs.ml"}
  "_build/install/default/lib/odoc/odoc/fs.mli" {"odoc/fs.mli"}
  "_build/install/default/lib/odoc/odoc/highlight_js.ml"
    {"odoc/highlight_js.ml"}
  "_build/install/default/lib/odoc/odoc/html_fragment.ml"
    {"odoc/html_fragment.ml"}
  "_build/install/default/lib/odoc/odoc/html_fragment.mli"
    {"odoc/html_fragment.mli"}
  "_build/install/default/lib/odoc/odoc/html_page.ml" {"odoc/html_page.ml"}
  "_build/install/default/lib/odoc/odoc/html_page.mli" {"odoc/html_page.mli"}
  "_build/install/default/lib/odoc/odoc/latex.ml" {"odoc/latex.ml"}
  "_build/install/default/lib/odoc/odoc/man_page.ml" {"odoc/man_page.ml"}
  "_build/install/default/lib/odoc/odoc/odoc_file.ml" {"odoc/odoc_file.ml"}
  "_build/install/default/lib/odoc/odoc/odoc_file.mli" {"odoc/odoc_file.mli"}
  "_build/install/default/lib/odoc/odoc/odoc_link.ml" {"odoc/odoc_link.ml"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc.a" {"odoc/odoc_odoc.a"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc.cma" {"odoc/odoc_odoc.cma"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc.cmi" {"odoc/odoc_odoc.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc.cmt" {"odoc/odoc_odoc.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc.cmx" {"odoc/odoc_odoc.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc.cmxa"
    {"odoc/odoc_odoc.cmxa"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc.ml" {"odoc/odoc_odoc.ml"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Compile.cmi"
    {"odoc/odoc_odoc__Compile.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Compile.cmt"
    {"odoc/odoc_odoc__Compile.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Compile.cmti"
    {"odoc/odoc_odoc__Compile.cmti"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Compile.cmx"
    {"odoc/odoc_odoc__Compile.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Css_file.cmi"
    {"odoc/odoc_odoc__Css_file.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Css_file.cmt"
    {"odoc/odoc_odoc__Css_file.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Css_file.cmx"
    {"odoc/odoc_odoc__Css_file.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Depends.cmi"
    {"odoc/odoc_odoc__Depends.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Depends.cmt"
    {"odoc/odoc_odoc__Depends.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Depends.cmti"
    {"odoc/odoc_odoc__Depends.cmti"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Depends.cmx"
    {"odoc/odoc_odoc__Depends.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Fs.cmi"
    {"odoc/odoc_odoc__Fs.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Fs.cmt"
    {"odoc/odoc_odoc__Fs.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Fs.cmti"
    {"odoc/odoc_odoc__Fs.cmti"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Fs.cmx"
    {"odoc/odoc_odoc__Fs.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Highlight_js.cmi"
    {"odoc/odoc_odoc__Highlight_js.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Highlight_js.cmt"
    {"odoc/odoc_odoc__Highlight_js.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Highlight_js.cmx"
    {"odoc/odoc_odoc__Highlight_js.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Html_fragment.cmi"
    {"odoc/odoc_odoc__Html_fragment.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Html_fragment.cmt"
    {"odoc/odoc_odoc__Html_fragment.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Html_fragment.cmti"
    {"odoc/odoc_odoc__Html_fragment.cmti"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Html_fragment.cmx"
    {"odoc/odoc_odoc__Html_fragment.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Html_page.cmi"
    {"odoc/odoc_odoc__Html_page.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Html_page.cmt"
    {"odoc/odoc_odoc__Html_page.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Html_page.cmti"
    {"odoc/odoc_odoc__Html_page.cmti"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Html_page.cmx"
    {"odoc/odoc_odoc__Html_page.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Latex.cmi"
    {"odoc/odoc_odoc__Latex.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Latex.cmt"
    {"odoc/odoc_odoc__Latex.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Latex.cmx"
    {"odoc/odoc_odoc__Latex.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Man_page.cmi"
    {"odoc/odoc_odoc__Man_page.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Man_page.cmt"
    {"odoc/odoc_odoc__Man_page.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Man_page.cmx"
    {"odoc/odoc_odoc__Man_page.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Odoc_file.cmi"
    {"odoc/odoc_odoc__Odoc_file.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Odoc_file.cmt"
    {"odoc/odoc_odoc__Odoc_file.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Odoc_file.cmti"
    {"odoc/odoc_odoc__Odoc_file.cmti"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Odoc_file.cmx"
    {"odoc/odoc_odoc__Odoc_file.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Odoc_link.cmi"
    {"odoc/odoc_odoc__Odoc_link.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Odoc_link.cmt"
    {"odoc/odoc_odoc__Odoc_link.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Odoc_link.cmx"
    {"odoc/odoc_odoc__Odoc_link.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Or_error.cmi"
    {"odoc/odoc_odoc__Or_error.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Or_error.cmt"
    {"odoc/odoc_odoc__Or_error.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Or_error.cmti"
    {"odoc/odoc_odoc__Or_error.cmti"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Or_error.cmx"
    {"odoc/odoc_odoc__Or_error.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Rendering.cmi"
    {"odoc/odoc_odoc__Rendering.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Rendering.cmt"
    {"odoc/odoc_odoc__Rendering.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Rendering.cmti"
    {"odoc/odoc_odoc__Rendering.cmti"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Rendering.cmx"
    {"odoc/odoc_odoc__Rendering.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Resolver.cmi"
    {"odoc/odoc_odoc__Resolver.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Resolver.cmt"
    {"odoc/odoc_odoc__Resolver.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Resolver.cmti"
    {"odoc/odoc_odoc__Resolver.cmti"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Resolver.cmx"
    {"odoc/odoc_odoc__Resolver.cmx"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Support_files.cmi"
    {"odoc/odoc_odoc__Support_files.cmi"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Support_files.cmt"
    {"odoc/odoc_odoc__Support_files.cmt"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Support_files.cmti"
    {"odoc/odoc_odoc__Support_files.cmti"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc__Support_files.cmx"
    {"odoc/odoc_odoc__Support_files.cmx"}
  "_build/install/default/lib/odoc/odoc/or_error.ml" {"odoc/or_error.ml"}
  "_build/install/default/lib/odoc/odoc/or_error.mli" {"odoc/or_error.mli"}
  "_build/install/default/lib/odoc/odoc/rendering.ml" {"odoc/rendering.ml"}
  "_build/install/default/lib/odoc/odoc/rendering.mli" {"odoc/rendering.mli"}
  "_build/install/default/lib/odoc/odoc/resolver.ml" {"odoc/resolver.ml"}
  "_build/install/default/lib/odoc/odoc/resolver.mli" {"odoc/resolver.mli"}
  "_build/install/default/lib/odoc/odoc/support_files.ml"
    {"odoc/support_files.ml"}
  "_build/install/default/lib/odoc/odoc/support_files.mli"
    {"odoc/support_files.mli"}
  "_build/install/default/lib/odoc/opam"
  "_build/install/default/lib/odoc/xref2/cfrag.ml" {"xref2/cfrag.ml"}
  "_build/install/default/lib/odoc/xref2/compile.ml" {"xref2/compile.ml"}
  "_build/install/default/lib/odoc/xref2/compile.mli" {"xref2/compile.mli"}
  "_build/install/default/lib/odoc/xref2/component.ml" {"xref2/component.ml"}
  "_build/install/default/lib/odoc/xref2/component.mli"
    {"xref2/component.mli"}
  "_build/install/default/lib/odoc/xref2/cpath.ml" {"xref2/cpath.ml"}
  "_build/install/default/lib/odoc/xref2/env.ml" {"xref2/env.ml"}
  "_build/install/default/lib/odoc/xref2/env.mli" {"xref2/env.mli"}
  "_build/install/default/lib/odoc/xref2/errors.ml" {"xref2/errors.ml"}
  "_build/install/default/lib/odoc/xref2/expand_tools.ml"
    {"xref2/expand_tools.ml"}
  "_build/install/default/lib/odoc/xref2/find.ml" {"xref2/find.ml"}
  "_build/install/default/lib/odoc/xref2/find.mli" {"xref2/find.mli"}
  "_build/install/default/lib/odoc/xref2/ident.ml" {"xref2/ident.ml"}
  "_build/install/default/lib/odoc/xref2/lang_of.ml" {"xref2/lang_of.ml"}
  "_build/install/default/lib/odoc/xref2/lang_of.mli" {"xref2/lang_of.mli"}
  "_build/install/default/lib/odoc/xref2/link.ml" {"xref2/link.ml"}
  "_build/install/default/lib/odoc/xref2/link.mli" {"xref2/link.mli"}
  "_build/install/default/lib/odoc/xref2/lookup_failures.ml"
    {"xref2/lookup_failures.ml"}
  "_build/install/default/lib/odoc/xref2/lookup_failures.mli"
    {"xref2/lookup_failures.mli"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2.a" {"xref2/odoc_xref2.a"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2.cma"
    {"xref2/odoc_xref2.cma"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2.cmi"
    {"xref2/odoc_xref2.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2.cmt"
    {"xref2/odoc_xref2.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2.cmx"
    {"xref2/odoc_xref2.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2.cmxa"
    {"xref2/odoc_xref2.cmxa"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2.ml"
    {"xref2/odoc_xref2.ml"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Cfrag.cmi"
    {"xref2/odoc_xref2__Cfrag.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Cfrag.cmt"
    {"xref2/odoc_xref2__Cfrag.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Cfrag.cmx"
    {"xref2/odoc_xref2__Cfrag.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Compile.cmi"
    {"xref2/odoc_xref2__Compile.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Compile.cmt"
    {"xref2/odoc_xref2__Compile.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Compile.cmti"
    {"xref2/odoc_xref2__Compile.cmti"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Compile.cmx"
    {"xref2/odoc_xref2__Compile.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Component.cmi"
    {"xref2/odoc_xref2__Component.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Component.cmt"
    {"xref2/odoc_xref2__Component.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Component.cmti"
    {"xref2/odoc_xref2__Component.cmti"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Component.cmx"
    {"xref2/odoc_xref2__Component.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Cpath.cmi"
    {"xref2/odoc_xref2__Cpath.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Cpath.cmt"
    {"xref2/odoc_xref2__Cpath.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Cpath.cmx"
    {"xref2/odoc_xref2__Cpath.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Env.cmi"
    {"xref2/odoc_xref2__Env.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Env.cmt"
    {"xref2/odoc_xref2__Env.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Env.cmti"
    {"xref2/odoc_xref2__Env.cmti"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Env.cmx"
    {"xref2/odoc_xref2__Env.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Errors.cmi"
    {"xref2/odoc_xref2__Errors.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Errors.cmt"
    {"xref2/odoc_xref2__Errors.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Errors.cmx"
    {"xref2/odoc_xref2__Errors.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Expand_tools.cmi"
    {"xref2/odoc_xref2__Expand_tools.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Expand_tools.cmt"
    {"xref2/odoc_xref2__Expand_tools.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Expand_tools.cmx"
    {"xref2/odoc_xref2__Expand_tools.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Find.cmi"
    {"xref2/odoc_xref2__Find.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Find.cmt"
    {"xref2/odoc_xref2__Find.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Find.cmti"
    {"xref2/odoc_xref2__Find.cmti"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Find.cmx"
    {"xref2/odoc_xref2__Find.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Ident.cmi"
    {"xref2/odoc_xref2__Ident.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Ident.cmt"
    {"xref2/odoc_xref2__Ident.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Ident.cmx"
    {"xref2/odoc_xref2__Ident.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Lang_of.cmi"
    {"xref2/odoc_xref2__Lang_of.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Lang_of.cmt"
    {"xref2/odoc_xref2__Lang_of.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Lang_of.cmti"
    {"xref2/odoc_xref2__Lang_of.cmti"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Lang_of.cmx"
    {"xref2/odoc_xref2__Lang_of.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Link.cmi"
    {"xref2/odoc_xref2__Link.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Link.cmt"
    {"xref2/odoc_xref2__Link.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Link.cmti"
    {"xref2/odoc_xref2__Link.cmti"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Link.cmx"
    {"xref2/odoc_xref2__Link.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Lookup_failures.cmi"
    {"xref2/odoc_xref2__Lookup_failures.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Lookup_failures.cmt"
    {"xref2/odoc_xref2__Lookup_failures.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Lookup_failures.cmti"
    {"xref2/odoc_xref2__Lookup_failures.cmti"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Lookup_failures.cmx"
    {"xref2/odoc_xref2__Lookup_failures.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Ref_tools.cmi"
    {"xref2/odoc_xref2__Ref_tools.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Ref_tools.cmt"
    {"xref2/odoc_xref2__Ref_tools.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Ref_tools.cmti"
    {"xref2/odoc_xref2__Ref_tools.cmti"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Ref_tools.cmx"
    {"xref2/odoc_xref2__Ref_tools.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Strengthen.cmi"
    {"xref2/odoc_xref2__Strengthen.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Strengthen.cmt"
    {"xref2/odoc_xref2__Strengthen.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Strengthen.cmx"
    {"xref2/odoc_xref2__Strengthen.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Subst.cmi"
    {"xref2/odoc_xref2__Subst.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Subst.cmt"
    {"xref2/odoc_xref2__Subst.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Subst.cmti"
    {"xref2/odoc_xref2__Subst.cmti"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Subst.cmx"
    {"xref2/odoc_xref2__Subst.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Tools.cmi"
    {"xref2/odoc_xref2__Tools.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Tools.cmt"
    {"xref2/odoc_xref2__Tools.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Tools.cmti"
    {"xref2/odoc_xref2__Tools.cmti"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Tools.cmx"
    {"xref2/odoc_xref2__Tools.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Type_of.cmi"
    {"xref2/odoc_xref2__Type_of.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Type_of.cmt"
    {"xref2/odoc_xref2__Type_of.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Type_of.cmti"
    {"xref2/odoc_xref2__Type_of.cmti"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Type_of.cmx"
    {"xref2/odoc_xref2__Type_of.cmx"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Utils.cmi"
    {"xref2/odoc_xref2__Utils.cmi"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Utils.cmt"
    {"xref2/odoc_xref2__Utils.cmt"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2__Utils.cmx"
    {"xref2/odoc_xref2__Utils.cmx"}
  "_build/install/default/lib/odoc/xref2/ref_tools.ml" {"xref2/ref_tools.ml"}
  "_build/install/default/lib/odoc/xref2/ref_tools.mli"
    {"xref2/ref_tools.mli"}
  "_build/install/default/lib/odoc/xref2/strengthen.ml"
    {"xref2/strengthen.ml"}
  "_build/install/default/lib/odoc/xref2/subst.ml" {"xref2/subst.ml"}
  "_build/install/default/lib/odoc/xref2/subst.mli" {"xref2/subst.mli"}
  "_build/install/default/lib/odoc/xref2/tools.ml" {"xref2/tools.ml"}
  "_build/install/default/lib/odoc/xref2/tools.mli" {"xref2/tools.mli"}
  "_build/install/default/lib/odoc/xref2/type_of.ml" {"xref2/type_of.ml"}
  "_build/install/default/lib/odoc/xref2/type_of.mli" {"xref2/type_of.mli"}
  "_build/install/default/lib/odoc/xref2/utils.ml" {"xref2/utils.ml"}
  "_build/install/default/lib/odoc/xref_test/common.ml"
    {"xref_test/common.ml"}
  "_build/install/default/lib/odoc/xref_test/odoc_xref_test.cma"
    {"xref_test/odoc_xref_test.cma"}
  "_build/install/default/lib/odoc/xref_test/odoc_xref_test.cmi"
    {"xref_test/odoc_xref_test.cmi"}
  "_build/install/default/lib/odoc/xref_test/odoc_xref_test.cmt"
    {"xref_test/odoc_xref_test.cmt"}
  "_build/install/default/lib/odoc/xref_test/odoc_xref_test.ml"
    {"xref_test/odoc_xref_test.ml"}
  "_build/install/default/lib/odoc/xref_test/odoc_xref_test__Common.cmi"
    {"xref_test/odoc_xref_test__Common.cmi"}
  "_build/install/default/lib/odoc/xref_test/odoc_xref_test__Common.cmt"
    {"xref_test/odoc_xref_test__Common.cmt"}
]
bin: "_build/install/default/bin/odoc"
share: [
  "_build/install/default/share/odoc/odoc-theme/default/highlight.pack.js"
    {"odoc-theme/default/highlight.pack.js"}
  "_build/install/default/share/odoc/odoc-theme/default/odoc.css"
    {"odoc-theme/default/odoc.css"}
]
doc: [
  "_build/install/default/doc/odoc/CHANGES.md"
  "_build/install/default/doc/odoc/LICENSE.md"
  "_build/install/default/doc/odoc/README.md"
  "_build/install/default/doc/odoc/odoc-pages/contributing.mld"
    {"odoc-pages/contributing.mld"}
  "_build/install/default/doc/odoc/odoc-pages/driver.mld"
    {"odoc-pages/driver.mld"}
  "_build/install/default/doc/odoc/odoc-pages/dune.mld"
    {"odoc-pages/dune.mld"}
  "_build/install/default/doc/odoc/odoc-pages/features.mld"
    {"odoc-pages/features.mld"}
  "_build/install/default/doc/odoc/odoc-pages/index.mld"
    {"odoc-pages/index.mld"}
  "_build/install/default/doc/odoc/odoc-pages/interface.mld"
    {"odoc-pages/interface.mld"}
  "_build/install/default/doc/odoc/odoc-pages/ocamldoc_differences.mld"
    {"odoc-pages/ocamldoc_differences.mld"}
  "_build/install/default/doc/odoc/odoc-pages/odoc_document.mld"
    {"odoc-pages/odoc_document.mld"}
  "_build/install/default/doc/odoc/odoc-pages/odoc_examples.mld"
    {"odoc-pages/odoc_examples.mld"}
  "_build/install/default/doc/odoc/odoc-pages/odoc_for_authors.mld"
    {"odoc-pages/odoc_for_authors.mld"}
  "_build/install/default/doc/odoc/odoc-pages/odoc_html.mld"
    {"odoc-pages/odoc_html.mld"}
  "_build/install/default/doc/odoc/odoc-pages/odoc_latex.mld"
    {"odoc-pages/odoc_latex.mld"}
  "_build/install/default/doc/odoc/odoc-pages/odoc_loader.mld"
    {"odoc-pages/odoc_loader.mld"}
  "_build/install/default/doc/odoc/odoc-pages/odoc_manpage.mld"
    {"odoc-pages/odoc_manpage.mld"}
  "_build/install/default/doc/odoc/odoc-pages/odoc_model.mld"
    {"odoc-pages/odoc_model.mld"}
  "_build/install/default/doc/odoc/odoc-pages/odoc_model_desc.mld"
    {"odoc-pages/odoc_model_desc.mld"}
  "_build/install/default/doc/odoc/odoc-pages/odoc_odoc.mld"
    {"odoc-pages/odoc_odoc.mld"}
  "_build/install/default/doc/odoc/odoc-pages/odoc_xref2.mld"
    {"odoc-pages/odoc_xref2.mld"}
  "_build/install/default/doc/odoc/odoc-pages/odoc_xref_test.mld"
    {"odoc-pages/odoc_xref_test.mld"}
  "_build/install/default/doc/odoc/odoc-pages/parent_child_spec.mld"
    {"odoc-pages/parent_child_spec.mld"}
]
libexec: [
  "_build/install/default/lib/odoc/document/odoc_document.cmxs"
    {"document/odoc_document.cmxs"}
  "_build/install/default/lib/odoc/examples/odoc_examples.cmxs"
    {"examples/odoc_examples.cmxs"}
  "_build/install/default/lib/odoc/html/odoc_html.cmxs"
    {"html/odoc_html.cmxs"}
  "_build/install/default/lib/odoc/latex/odoc_latex.cmxs"
    {"latex/odoc_latex.cmxs"}
  "_build/install/default/lib/odoc/loader/odoc_loader.cmxs"
    {"loader/odoc_loader.cmxs"}
  "_build/install/default/lib/odoc/manpage/odoc_manpage.cmxs"
    {"manpage/odoc_manpage.cmxs"}
  "_build/install/default/lib/odoc/model/odoc_model.cmxs"
    {"model/odoc_model.cmxs"}
  "_build/install/default/lib/odoc/model_desc/odoc_model_desc.cmxs"
    {"model_desc/odoc_model_desc.cmxs"}
  "_build/install/default/lib/odoc/odoc/odoc_odoc.cmxs"
    {"odoc/odoc_odoc.cmxs"}
  "_build/install/default/lib/odoc/xref2/odoc_xref2.cmxs"
    {"xref2/odoc_xref2.cmxs"}
]
