opam-version: "2.0"
lib: [
  "_build/install/default/lib/randomconv/META"
  "_build/install/default/lib/randomconv/dune-package"
  "_build/install/default/lib/randomconv/opam"
  "_build/install/default/lib/randomconv/randomconv.a"
  "_build/install/default/lib/randomconv/randomconv.cma"
  "_build/install/default/lib/randomconv/randomconv.cmi"
  "_build/install/default/lib/randomconv/randomconv.cmt"
  "_build/install/default/lib/randomconv/randomconv.cmti"
  "_build/install/default/lib/randomconv/randomconv.cmx"
  "_build/install/default/lib/randomconv/randomconv.cmxa"
  "_build/install/default/lib/randomconv/randomconv.ml"
  "_build/install/default/lib/randomconv/randomconv.mli"
]
doc: [
  "_build/install/default/doc/randomconv/CHANGES.md"
  "_build/install/default/doc/randomconv/LICENSE.md"
  "_build/install/default/doc/randomconv/README.md"
]
libexec: "_build/install/default/lib/randomconv/randomconv.cmxs"
