opam-version: "2.0"
lib: [
  "_build/install/default/lib/tls-mirage/META"
  "_build/install/default/lib/tls-mirage/dune-package"
  "_build/install/default/lib/tls-mirage/opam"
  "_build/install/default/lib/tls-mirage/tls_mirage.a"
  "_build/install/default/lib/tls-mirage/tls_mirage.cma"
  "_build/install/default/lib/tls-mirage/tls_mirage.cmi"
  "_build/install/default/lib/tls-mirage/tls_mirage.cmt"
  "_build/install/default/lib/tls-mirage/tls_mirage.cmti"
  "_build/install/default/lib/tls-mirage/tls_mirage.cmx"
  "_build/install/default/lib/tls-mirage/tls_mirage.cmxa"
  "_build/install/default/lib/tls-mirage/tls_mirage.ml"
  "_build/install/default/lib/tls-mirage/tls_mirage.mli"
]
doc: [
  "_build/install/default/doc/tls-mirage/CHANGES.md"
  "_build/install/default/doc/tls-mirage/LICENSE.md"
  "_build/install/default/doc/tls-mirage/README.md"
]
libexec: "_build/install/default/lib/tls-mirage/tls_mirage.cmxs"
