.\" Pipe this output to groff -Tutf8 | less
.\"
.mso an.tmac
.TH "DUNE-CACHE" 1 "" "Dune 2.9.2" "Dune Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
dune\N'45'cache \N'45' Manage the shared artifacts cache
.SH SYNOPSIS
.P
\fBdune cache\fR [\fIOPTION\fR]\N'46'\N'46'\N'46' [\fIACTION\fR]
.SH DESCRIPTION
.P
Dune is able to share build artifacts between workspaces\N'46' \fBdune cache\N'45'daemon\fR is a daemon that runs in the background and manages this shared cache\N'46' For instance, it makes sure that it does not grow too big and try to maximise sharing between the various workspaces that are using the shared cache\N'46'
.P
The daemon is automatically started by Dune when the shared cache is enabled\N'46' You do not need to run this command manually\N'46'
.SH ACTIONS
.P
\fBstart\fR starts the daemon if not already running\N'46'
.P
\fBstop\fR stops the daemon\N'46'
.P
\fBtrim\fR removes oldest files from the cache to free space\N'46'
.SH ARGUMENTS
.TP 4
\fIACTION\fR
The cache\N'45'daemon action to perform (one of `start\N'39', `stop\N'39' or `trim\N'39')
.SH OPTIONS
.TP 4
\fB\N'45'\N'45'exit\N'45'no\N'45'client\fR (absent \fBDUNE_CACHE_EXIT_NO_CLIENT\fR env)
Whether to exit once all clients have disconnected
.TP 4
\fB\N'45'f\fR, \fB\N'45'\N'45'foreground\fR
Whether to start in the foreground or as a daemon
.TP 4
\fB\N'45'\N'45'help\fR[=\fIFMT\fR] (default=auto)
Show this help in format \fIFMT\fR\N'46' The value \fIFMT\fR must be one of `auto\N'39', `pager\N'39', `groff\N'39' or `plain\N'39'\N'46' With `auto\N'39', the format is `pager` or `plain\N'39' whenever the \fBTERM\fR env var is `dumb\N'39' or undefined\N'46'
.TP 4
\fB\N'45'\N'45'port\N'45'file\fR=\fIPATH\fR (absent=/run/user/1000/dune\N'45'cache\N'45'daemon/dune\N'45'cache\N'45'daemon/port)
The file to read/write the daemon port from/to\N'46'
.TP 4
\fB\N'45'\N'45'root\fR=\fIPATH\fR (absent=/home/maiste/\N'46'cache/dune/db)
Root of the dune cache
.TP 4
\fB\N'45'\N'45'size\fR=\fIBYTES\fR
size to trim the cache to
.TP 4
\fB\N'45'\N'45'trimmed\N'45'size\fR=\fIBYTES\fR
size to trim from the cache
.TP 4
\fB\N'45'\N'45'version\fR
Show version information\N'46'
.SH COMMON OPTIONS
.P
These options are common to all commands\N'46'
.TP 4
\fB\N'45'\N'45'config\N'45'file\fR=\fIFILE\fR
Load this configuration file instead of the default one\N'46'
.TP 4
\fB\N'45'\N'45'display\fR=\fIMODE\fR
Control the display mode of Dune\N'46' See \fBdune\N'45'config(5)\fR for more details\N'46'
.TP 4
\fB\N'45'\N'45'no\N'45'config\fR
Do not load the configuration file
.TP 4
\fB\N'45'\N'45'verbose\fR
Same as \fB\N'45'\N'45'display verbose\fR
.SH MORE HELP
.P
Use `\fBdune\fR \fICOMMAND\fR \N'45'\N'45'help\N'39' for help on a single command\N'46'
.SH ENVIRONMENT
.P
These environment variables affect the execution of \fBcache\fR:
.TP 4
\fBDUNE_CACHE_EXIT_NO_CLIENT\fR
Whether to exit once all clients have disconnected
.SH BUGS
.P
Check bug reports at https://github\N'46'com/ocaml/dune/issues